FIX
- cmake debug mode build failed with errors "... requires ISA extension ‘sve’"
- GCC11 compile error "... qulacs/src/csim/update_ops_named_FusedSWAP.cpp:79:20: error: call of overloaded ‘abs(UINT)’ is ambiguous"